# Generated by Django 3.0.4 on 2020-03-25 09:53

import cms.models
import cms.mixins
import cms.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', cms.fields.CharField(verbose_name='page')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('number', models.PositiveIntegerField(blank=True, verbose_name='number')),
                ('menu', models.BooleanField(default=True, verbose_name='visible in menu')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
                ('google_keywords', models.TextField(blank=True, verbose_name='Google keywords')),
                ('google_description', models.TextField(blank=True, verbose_name='Google description')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['number'],
                'abstract': False,
            },
            bases=(cms.mixins.Numbered, models.Model),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', cms.fields.CharField(verbose_name='section')),
                ('type', cms.fields.CharField(verbose_name='type')),
                ('number', models.PositiveIntegerField(blank=True, verbose_name='number')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='image')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Paste a YouTube, Vimeo, or SoundCloud link', verbose_name='video')),
                ('href', cms.fields.CharField(blank=True, verbose_name='link')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='copyshop.Page')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'ordering': ['number'],
                'abstract': False,
            },
            bases=(cms.mixins.Numbered, models.Model),
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', cms.fields.CharField(choices=[('Ma', 'Maandag'), ('Di', 'Dinsdag'), ('Wo', 'Woensdag'), ('Do', 'Donderdag'), ('Vr', 'Vrijdag'), ('Za', 'Zaterdag'), ('Zo', 'Zondag')], verbose_name='Dag')),
                ('hours', cms.fields.CharField(verbose_name='Geopend')),
                ('note', cms.fields.CharField(blank=True, verbose_name='Opmerking')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='copyshop.Section')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', cms.fields.CharField(verbose_name='titel')),
                ('description', cms.fields.CharField(blank=True, verbose_name='Beschrijving')),
                ('file', models.FileField(upload_to='', verbose_name='Bestand')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='copyshop.Section')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
