# Generated by Django 3.0.4 on 2020-03-25 12:08

import cms.models
import cms.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyshop', '0002_auto_20200325_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', cms.fields.CharField(verbose_name='naam')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('address', models.TextField(verbose_name='adres')),
                ('phone', cms.fields.CharField(verbose_name='telefoonnummer')),
                ('notes', models.TextField(blank=True, verbose_name='opmerkingen')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='totaalbedrag')),
                ('status', models.CharField(choices=[('open', 'nog niet betaald'), ('canceled', 'betaling geannuleerd'), ('expired', 'betaling verlopen'), ('failed', 'betaling mislukt'), ('paid', 'betaald'), ('pending', 'in behandeling'), ('shipped', 'verstuurd')], default='open', max_length=32, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='aangemaakt')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='gewijzigd')),
                ('payment_url', models.URLField(blank=True, verbose_name='iDeal link')),
            ],
            options={
                'verbose_name': 'bestelling',
                'verbose_name_plural': 'bestellingen',
                'ordering': ['-created'],
            },
        ),
    ]
