# Generated by Django 3.0.4 on 2020-03-25 17:36

import cms.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copyshop', '0004_auto_20200325_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=cms.fields.CharField(blank=True),
        ),
    ]
