# Generated by Django 3.0.4 on 2020-03-25 20:22

import cms.fields
import copyshop.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copyshop', '0006_auto_20200325_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=cms.fields.CharField(default=copyshop.models.get_token),
        ),
    ]
