# Generated by Django 3.0.4 on 2020-03-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BWPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='totaal aantal')),
                ('price', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='prijs per zijde')),
            ],
            options={
                'verbose_name': 'Zwart/wit prijs',
                'verbose_name_plural': 'Zwart/wit prijzen',
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='FCPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='totaal aantal')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='prijs per zijde')),
            ],
            options={
                'verbose_name': 'Kleurenprijs',
                'verbose_name_plural': 'Kleurenprijzen',
                'ordering': ['amount'],
            },
        ),
    ]
